**目录**  

- [捕获异常](#捕获异常)
- [获取异常对象](#获取异常对象)
- [匹配所有异常](#匹配所有异常)
- [自定义异常](#自定义异常)
- [函数调用里面的异常](#函数调用里面的异常)
- [try-finaly语句](#try-finaly语句)
- [断言(assert)](#断言assert)


**处理python程序在运行中出现的异常和错误：**
- 异常处理
- 断言(Assertions) 

# 捕获异常
如果我们在编码的时候，就预料到了某些代码运行时可能出现某些异常，就可以使用 try...except... 这样的方法来捕获和处理异常。

```python
try:
    choice = input('输入你的选择:')
    if choice == '1':
        100/0
    elif choice == '2':
        [][2]
except ZeroDivisionError:
    print ('出现 ZeroDivisionError')
except IndexError  :
    print ('出现 IndexError')
```

try 下面缩进的3行代码可以看成是 保护区 中的代码。
如果执行保护区中代码时，出现异常，解释器会结束保护区中后续代码的执行，并检查这个异常的类型是否匹配后面的except 语句中声明的类型。
如果匹配上，解释器知道程序对此种异常是预料到的，并且有对应的处理方案，也就是匹配的except下面缩进的代码。解释器就执行匹配的except下面缩进的代码，不会因此中止程序。

# 获取异常对象
我们使用except 语句匹配异常类型的时候， 可以使用as关键字，后面加一个变量名，如下所示：


```python
try:
    100/0
except ZeroDivisionError as e:
    print(f'异常对象信息:{e}')

```
这样，运行代码的时候，当try中的语句产生异常对象时，就会 把产生的异常对象赋值给as后的变量。

# 匹配所有异常
如果我们在写一段代码的时候，不知道这段代码会抛出什么样的异常，并且我们不希望程序因为异常而中止。
这时我们可以匹配所有类型的异常，这样任何类型的异常发生都不会终止程序了。 如下：
```python
try:
    100/0
except Exception as e:
    print(f'异常对象信息:{e}')

#还有一种更简单的方法
import traceback
try:
    100/0
except:
    print('出现异常')
    #如果想知道异常的详细信息
    print(traceback.format_exc())
#在except下面缩进代码中，使用traceback模块里面的format_exc函数，可以显示异常的信息 和 异常产生处的函数调用栈的信息。
```
因为所有的异常都是 Exception 的子类。 所以 Exception能匹配所有类型的异常

# 自定义异常
异常类型都是 继承自Exception的类，表示各种类型的错误。  
我们也可以自己定义异常，比如我们写一个用户注册的函数， 要求用户输入的电话号码只能是中国的电话号码，并且电话号码中不能有非数字字符。

```python
# 异常对象，代表电话号码有非法字符
class InvalidCharError(Exception):
    pass

# 异常对象，代表电话号码非中国号码
class NotChinaTelError(Exception):
    pass

#定义了上面的异常，当用户输入电话号码时，出现相应错误的时候，我们就可以使用raise 关键字来抛出对应的自定义异常

def register(phone):
    tel = input('请输入电话号码:')
    #如果有非数字字符
    if not tel.isdigit():
        raise InvalidCharError('电话号码中不能有非数字字符')
    #如果非中国号码
    if not tel.startswith('86'):
        raise NotChinaTelError('电话号码非中国号码')
    return tel

try:
    ret = register('123456789012345678901')
except InvalidCharError:
    print('电话号码中有错误的字符')
except NotChinaTelError:
    print('电话号码非中国号码')
# 调用register函数
register('123')
register('12345678901')
register('123456789012345678901')
```

**多种异常自定义**  
当创建一个模块有可能抛出多种不同异常时，一种通常的做法是为这个包建立一个基础异常类，然后基于这个基础类为不同的错误情况创建不同的子类：

```python

class Error(Exception):
    pass

class InputError(Error):
    def __init__(self, expression, message):
        self.expression = expression
        self.message = message

class TransitionError(Error):
    def __init__(self, previous,expression, message):
        self.previous = previous
        self.expression = expression
        self.message = message

# 调用
def foo(s):
    n = int(s)
    if n == 0:
        raise InputError(s, 'Cannot divide by zero')
    if n < 0:
        raise TransitionError("error",s, 'Invalid transition')

#大多数的异常的名字都以Error结尾，就跟标准的异常命名一样
```
# 函数调用里面的异常
```python
def level_3():
    print ('进入 level_3')
    a = [0]
    b = a[1]
    print ('离开 level_3')

def level_2():
    print ('进入 level_2')
    level_3()
    print ('离开 level_2')

def level_1():
    print ('进入 level_1')
    level_2()
    print ('离开 level_1')
level_1()
print('程序正常退出') 
```

可以发现，上面还有输出的信息，说明了这行引起异常的代码, 是怎样被 一层层 的调用进来的。
这就是**函数调用栈的信息**
当异常在函数中产生的时候，解释器会终止当前代码的执行， 查看当前函数是否 声明了该类型异常的 except 处理，如果有，就执行， 随后继续执行代码。
如果当前函数没有 声明了该类型异常的处理， 就会中止当前函数的执行，退出到调用该函数的上层函数中， 查看上层是否有 声明了该类型异常的 except 处理。如果有，就执行该异常匹配处理。 随后继续执行代码。
如果上层函数也没有 该类型异常的匹配处理， 就会到继续到再上层的函数查看是否有 该类型异常的匹配处理。
如此这般，直到到了最外层的代码。 如果依然没有 声明了该类型异常处理，就终止当前代码的执行。

```python
import traceback

def level_3():
    print ('进入 level_3')
    try:
        a = [0]
        b = a[1]
    except :
        print(f'未知异常:{traceback.format_exc()}')
    print ('离开 level_3')
def level_2():
    print ('进入 level_2')
    level_3()
    print ('离开 level_2')

def level_1():
    print ('进入 level_1')
    level_2()
    print ('离开 level_1')
level_1()
print('程序正常退出')
```

# try-finaly语句

```python
try:
    print('执行代码')
except:
    print('发生异常时执行的代码')
else:
    print('没有异常时执行的代码')

finally:
    print('无论是否发生异常都会执行的代码')
```

# 断言(assert)
python assert(断言)用于判断一个表达式，在表达式条件为False的时候触发异常。  
断言可以在条件不满足程序运行的情况下直接返回错误，而不必等待程序运行后出现崩溃的情况，
例如我们的代码只能在 Linux 系统下运行，可以先判断当前系统是否符合条件。

语法：
```python
assert expression

# 等价于
if not expression:
    raise AssertionError

# assert 后面也可以紧跟参数：
assert expression[,arguments]

# 等价于
if not expression:
    raise AssertionError(arguments)   
```

以下实例判断当前系统是否为Linux,如果不满足条件则直接触发异常，不必执行接下来的代码:  


```python   
import sys
assert ( 'Linux' in sys.platform),"改代码只能在Linux下运行""
```